theme = "dark_plus"

[editor]
line-number = "relative"
rulers = [79, 80, 88, 100]
bufferline = "always"
auto-pairs = false
cursorline = true
insert-final-newline = true

[editor.lsp]
# Too often in the way, moved to a keyboard shortcut
auto-signature-help = false

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = false

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "primary-selection-length", "file-encoding"]

[keys.insert]
C-space = "signature_help"

[keys.normal]
# ret = "goto_word"

[keys.normal.space]
q = ":buffer-close"
Q = ":buffer-close!"
o = "file_picker_in_current_buffer_directory"

[keys.normal."\\"]
p = "@ghecpick<esc>"
r = "@ghecreword<esc>"
e = "@ghecedit<esc>"
s = "@ghecsquash<esc>"
f = "@ghecfixup<esc>"
d = "@ghecdrop<esc>"
